### ISSUE TITLE
ELF文件结构图制作的太赞了 请问是怎么制作的

### ISSUE THREAD

**Issue by Cxk4ng** [jianhong-li/ElfReader#1]
> 这个图做的太棒了 结构清晰明了
> 可以清晰的指向每个结构展开描述
> 是用什么软件制作的 太赞了

![解析结果图片](https://raw.githubusercontent.com/jianhong-li/ElfReader/main/ELF_FORMAT.jpg)

**Comment by jianhong-li** [comment]
drawio 画的. : https://draw.io
